language: node_js

node_js:
- 4.2.3

matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.1.1

before_script:
- npm install -g bower grunt-cli
- bower install

services: mongodb

before_deploy:
  - ls -ltra
  - grunt build
  - ls -ltra
  - rm -rf server client .tmp e2e package.json
  - ls -ltra
  - mv dist/* .
  - ls -ltra
  - rm -rf dist
  - ls -ltra

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: KEI+Q8pnB/u9UKfH0LKgkf4gikMyyxWNv0FNkv2h1B+FbayuXq8uM3g/Ej6moLc2A6n0BLBoObSwq9yCEcj/kVRwCjGos69gF6FCNnbkTUurBXiUpnrHrLYYsVeaAyNzUsjJt/PAOZ4UnolGg8GkdMo9rVvx9eJ6DHCKchlghcTwg6FS/IyddVGR/uSf0eUs6jsJJvDZz0LKE7TI/GMyBKnLf7rVpNQ4QnGzKUBZqb9KqjHKtnc/EVB19cq1i/UpU/owAPqzaD6g/jeRpf77iJUv0VunvFabz3O0KUmqZJzuCjBEBNItM3LCssFMJCcsOTKzGiqmYQ+dqKd9pC+mGhVIUcURVmzPdKIOBNjzl10+1qO+eBKfwZ4Bo4JK+u1Aw+hO48noqSqnTY0AMVWek95VdGwtJPuAjrEooCScDu9iI0XsK86/sTqooBUuURWDxl0av83wm1VCTeo5NeAZtFNgzBDm2LkgvTsTetuewXlYiAVXpTYvKDcL5Uo+o9eHtSd6JUWyRszXNxE3I/eIjrnQixGhULCops0ZAwzFwUH9+IM3ENz9g1/TjlYIDTeFNgFUZJ8tbedKuLUFVqW769EG77Q5pEGsTIugTqp6FyNYT8/42wIlNNmZ7pGD0DmaMNSrjBup8xgK7ZEz/s9qvxr4OUObx6X2A2VnKKmNbfo=

after_script:
  - npm install codeclimate-test-reporter
  #TODO merge integration and unit tests coverage reports
  - codeclimate-test-reporter < ./coverage/server/integration/lcov.info

addons:

  code_climate:
    repo_token: c0f8ef3f1117d8416655a3aa7c8f89f2afec95569c1deb67d5be1168be4d4674

  sauce_connect:
    username: "Kauabunga"
    access_key:
      secure: "mMcIhcjVHh5PLILu/9t4KZ8n3ffZUNC8zRMUYMga1oWoc3+2rHLW3lpIBSZisNYI3nYiZxeqWsJaDp513dIot6o6ZiiXL9ehDw0wG7iROKnqrrarm0+TCtr+1NLAZfNVu0ZyC5IwIWZnIpXRNX06BMJIWwJj59eKrgKxEPSh2ys/oHYrmfcThexk/m+iZj/wLP3DmRsT9CqQTBH8fgfxilytNACEyw/zigJcVhVhCUViJ8rl1G3ReqgcNcjYS5y4UIfVS/+eIef40dW/8fvSHeWR24J5/2E02sACf6kHue006C6xI72ku/eDI1LTevkeCN/THpyA93R40bSdPA6aqzUckLLc2IdfuLSUq+fCPqnmavdsCjfri5H9LYm+QOUCxrA0bcJienSV9SmsqjlqlHofq+fiNy4hmxz4iypJxGy6m4wtTdUfW4NDtcS6rXCcG4PJf02eDZVHou6tsk6MuxKIp+rSVIuGuD89df3AQ+r5wntfr/rFmBwyeiBO4DnkFc3PuMOyaEReDHbYDZWqTZiLPPKQwxPFvCS76E8rfaOnLiH/gRz+UajT2oeEM+AXwJ7Rw7wPsom+NZNMOIDYlHKG6GosVNAPTpr6fOI3TGe9XF4yZBOy6ji1+U0yi9QH7pWUXdq7v6sb9/XR+NQQTUHNvfo2NBKW6ljKAwYzoAc="
